CREATE TABLE SHIPWRECK(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(2000),
	CONDITION VARCHAR(255),
	DEPTH INT,
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	YEAR_DESCOVERED INT,	
);

CREATE TABLE USUARIO(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	CARGO VARCHAR(255),
	REGISTRO VARCHAR(255),
);